### ISSUE TITLE
add codecov

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/gulp-param#22]

**Comment by przemcio** [comment]
Do you have any experience with istambul ?  I'm not sure whether I should put it as dev dependecy or a regular.

**Comment by stoeffel** [comment]
istanbul is a devdependency. I use it in some of my modules.

**Comment by stoeffel** [comment]
check out stoeffel/compose-function for example.

**Comment by przemcio** [comment]
thx

**Comment by przemcio** [comment]
But you use coveralls. So maybe there is no sense to introduce new tool to grab coverage ?

**Comment by stoeffel** [comment]
Sorry I'm on my mobile. Hopefully I have time tomorrow.

**Comment by stoeffel** [comment]
This should work:

```bash
install:
  - npm install -D codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov

**Comment by stoeffel** [comment]
and we need mocha-lcov-reporte as a dev dep as well.
