### ISSUE TITLE
seems to always puts gulp tasks into async mode

### ISSUE THREAD

**Issue by nrser** [stoeffel/gulp-param#30]
hey, i'm just getting started with gulp, so forgive me if i'm missing something here, but this stumped me for hours and i think i figured it out... it seems that gulp-param always puts gulp into async mode by accepting a callback parameter in the task definition function passed to `gulp.task`.

first off, i'm on gulp 3.9.1 and gulp-param 1.0.3.

check, this out, from the README code:

``` javascript
gulp.task('dep', function(debug) {
  console.log(debug); // => true
});

gulp.task('build', ['dep'], function(debug, tag) {
  console.log(debug); // => true
  console.log(tag); // => 'v1.0.0'
});
```

```
$ gulp build
[21:54:41] Using gulpfile ~/.../gulpfile.js
[21:54:41] Starting 'dep'...
undefined
```

notice that even though i'm invoking `build`, which depends on `dep`, only `dep` gets run and we never get to `build`.

this is because even though neither the `build` or `dep` task functions accept the `callback` parameter, the original `gulp.task` is getting called with one (the `wrappedTaskFunction` which is a function that always accepts the `originalCallbackFunction` parameter:

https://github.com/stoeffel/gulp-param/blob/v1.0.3/index.js#L33

if you modify the README code to use the callbacks it works as expected:

```
gulp.task('dep', function(debug, callback) {
  console.log(debug); // => true
  callback();
});

gulp.task('build', ['dep'], function(debug, tag, callback) {
  console.log(debug); // => true
  console.log(tag); // => 'v1.0.0'
  callback();
});
```

```
$ gulp build
[22:06:21] Using gulpfile ~/.../gulpfile.js
[22:06:21] Starting 'dep'...
undefined
[22:06:21] Finished 'dep' after 1.09 ms
[22:06:21] Starting 'build'...
undefined
undefined
[22:06:21] Finished 'build' after 231 μs
```

i think you only want to provide a callback function to the original `gulp.task` when the user-provided task function has the named callback parameter in it's arguments (`callback` by default).

i will probably take a stab at fixing this and sending you a PR, but i'm super busy and just wasted 2-3 hours on this, so i wanted to get this up here in the meantime to try and save time and struggle for anyone else in case i never get to it.

thanks for the module by the way :)

**Comment by przemcio** [comment]
Closing as it is solved in #31
