### ISSUE TITLE
Does this work with ES6?

### ISSUE THREAD

**Issue by mlennon3** [stoeffel/gulp-param#5]
When I use gulp-param with a  ```require('babel/register'); ``` in my gulpfile, I get an error:

``` TypeError: Cannot redefine property: startsWith```

This seems to be a problem with the startsWith polyfill, is there any way around this?

**Comment by stoeffel** [comment]
`gulp-param` works with es6 for me, checkout this [making gulp work with es6](https://github.com/gulpjs/gulp/issues/830#issuecomment-123601869)

**Comment by stoeffel** [comment]
@mlennon3 Did it work now?

**Comment by stoeffel** [comment]
@mlennon3 Did it work now?

**Comment by mlennon3** [comment]
Yup, thanks!
